"""StorageBackend protocol: unified interface for all data persistence."""

from typing import Protocol, runtime_checkable

from pneuma_core.models.character import Character
from pneuma_core.models.change_record import ChangeRecord
from pneuma_core.models.emotion import EmotionalState
from pneuma_core.models.goals import GoalTree
from pneuma_core.models.memory import EpisodicMemory, SemanticMemory
from pneuma_core.models.relation import Relation
from pneuma_core.models.todo import TodoItem


@runtime_checkable
class StorageBackend(Protocol):
    """全データの統合ストレージインターフェース.

    Character, Memory, Goals, State, ChangeLog の CRUD を提供。
    """

    # Character
    async def save_character(self, character: Character) -> None: ...
    async def get_character(self, character_id: str) -> Character | None: ...
    async def list_characters(self) -> list[Character]: ...

    # Memory
    async def save_episodic_memory(self, memory: EpisodicMemory) -> None: ...
    async def get_episodic_memories(self, character_id: str) -> list[EpisodicMemory]: ...
    async def find_similar_memories(
        self, character_id: str, embedding: list[float], threshold: float
    ) -> list[EpisodicMemory]: ...
    async def save_semantic_memory(self, memory: SemanticMemory) -> None: ...
    async def update_semantic_memory(self, memory: SemanticMemory) -> None: ...
    async def delete_semantic_memory(self, memory_id: str) -> None: ...
    async def get_semantic_memories(self, character_id: str) -> list[SemanticMemory]: ...

    # Goals
    async def save_goals(self, character_id: str, goals: GoalTree) -> None: ...
    async def get_goals(self, character_id: str) -> GoalTree | None: ...

    # State
    async def save_emotional_state(
        self, character_id: str, state: EmotionalState
    ) -> None: ...
    async def get_emotional_state(
        self, character_id: str
    ) -> EmotionalState | None: ...

    # ChangeLog
    async def save_change(self, change: ChangeRecord) -> None: ...
    async def get_changes(
        self, character_id: str, limit: int = 100
    ) -> list[ChangeRecord]: ...

    # Todo
    async def save_todo(self, todo: TodoItem) -> None: ...
    async def get_todo(self, todo_id: str) -> TodoItem | None: ...
    async def list_todos(
        self, status: str | None = None, label: str | None = None,
        owner_id: str | None = None,
    ) -> list[TodoItem]: ...
    async def update_todo(self, todo: TodoItem) -> None: ...
    async def delete_todo(self, todo_id: str) -> None: ...

    # Relation
    async def save_relation(self, relation: Relation) -> None: ...
    async def get_relation(self, relation_id: str) -> Relation | None: ...
    async def list_relations(
        self, owner_id: str | None = None,
    ) -> list[Relation]: ...
